export const technologies = [
  ["Ably", "https://ably.com/"],
  ["Bun", "https://bun.sh/"],
  ["Clerk", "https://clerk.com/"],
  ["Cursor", "https://www.cursor.com/"],
  ["Drizzle ORM", "https://orm.drizzle.team/"],
  ["ESLint", "https://eslint.org/"],
  ["Helicone", "https://www.helicone.ai/"],
  ["Inngest", "https://www.inngest.com/"],
  ["Jupyter", "https://jupyter.org/"],
  ["Neon", "https://neon.tech/"],
  ["OpenAI", "https://openai.com/"],
  ["PostgreSQL", "https://www.postgresql.org/"],
  ["Prettier", "https://prettier.io/"],
  ["Tailwind CSS", "https://tailwindcss.com/"],
  ["TanStack Start", "https://tanstack.com/"],
  ["TypeScript", "https://www.typescriptlang.org/"],
  ["Vapi", "https://vapi.ai/"],
  ["Vitest", "https://vitest.dev/"],
  ["Zod", "https://zod.dev/"],
] as const satisfies [string, string][];
